version: '3.9'

# Refer https://www.ibm.com/docs/en/db2/11.5?topic=system-macos

# On Mac Apple silicon, had to run "export DOCKER_DEFAULT_PLATFORM=linux/amd64" before executing docker-compose commands to start the container
# we can also set it to x86 "export DOCKER_DEFAULT_PLATFORM=linux/x86_64"
# Else you may see this type of error "no matching manifest for linux/arm64/v8 in the manifest list entries"
# you may verify available OS Manifests using "docker manifest inspect icr.io/db2_community/db2:11.5"
# docker manifest inspect icr.io/db2_community/db2

services:

  fin_dev_db2:
    # image: icr.io/db2_community/db2:11.5
    image: icr.io/db2_community/db2
    platform: linux/amd64
    container_name: fin_dev_db2
    restart: always
    privileged: true
    # volumes:
    #   - $PWD/data:/database/
    #   - $PWD/user_home:/home/user/
    volumes:
      - db2_database_data:/database
    #   - db2server_ce:/database
    #   - user_home:/home/user
    ports:
      - 50000:50000
    environment:
      LICENSE: accept
      DB2INSTANCE: db2admin
      DB2INST1_PASSWORD: Financials1
      DBNAME: db2admin
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: true
      REPODB: false
      IS_OSXFS: true
      PERSISTENT_HOME: true
      HADR_ENABLED: false #High Availability Disaster Recoever, we don't need it locally

volumes:
  db2_database_data:
    driver: local

# volumes:
#   db2server_ce:
#     driver: local
#     driver_opts:
#       type: none
#       device: $PWD/data/database
#       o: bind
#   user_home:
#     driver: local
#     driver_opts:
#       type: none
#       device: $PWD/user_home
#       o: bind
    

# First time, get into the container, and run some of these below commands
# "su db2admin" : for using DB instance db2admin
# "db2admin" : starts the DB2 instance as sample

# db2 # enter into db2 prompt
# connect to db2admin
# SELECT CURRENT SERVER FROM SYSIBM.SYSDUMMY1; # Helps you know which database you have connected
# list tables
# SELECT COOUNT(*) FROM PURCHASEORDER; # some sample query 

# Use a db2 ide like DBeaver and create schema db2admin and then create tables and select to test
# create a table purchase order with purchase_order_id, desc, amount and date
# CREATE TABLE PURCHASEORDER (PURCHASE_ORDER_ID INT NOT NULL PRIMARY KEY, DESCRIPTION VARCHAR(50), AMOUNT DECIMAL(10,2), DATE DATE);
# INSERT INTO PURCHASEORDER values (1, 'Purchase Order 1', 100.00, '2021-01-01');
# INSERT INTO PURCHASEORDER values (2, 'Another Purchase Order', 30.09, '2021-01-02');insert into purchaseorder values (1, 'Purchase Order 1', 100.00, '2021-01-01');
